'use client';

import { icons, LucideProps } from 'lucide-react';

import { cn } from '@/lib/utils';

// Convert kebab-case or snake_case to PascalCase for Lucide icon lookup
function toIconName(name: string): string {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

interface IconDisplayProps extends Omit<LucideProps, 'ref' | 'name'> {
  name: string | null | undefined;
  fallback?: React.ReactNode;
}

export function IconDisplay({ name, fallback, className, ...props }: IconDisplayProps) {
  if (!name) {
    return fallback ? <>{fallback}</> : null;
  }

  // Try to find the icon with different name formats
  const iconName = toIconName(name);
  const IconComponent = icons[iconName as keyof typeof icons];

  if (!IconComponent) {
    // Try the original name as-is (in case it's already PascalCase)
    const directIcon = icons[name as keyof typeof icons];
    if (directIcon) {
      const DirectIconComponent = directIcon;
      return <DirectIconComponent className={cn('h-4 w-4', className)} {...props} />;
    }
    return fallback ? <>{fallback}</> : <span className="text-xs text-muted-foreground">{name}</span>;
  }

  return <IconComponent className={cn('h-4 w-4', className)} {...props} />;
}

// Export icon names for the picker
export function getIconNames(): string[] {
  return Object.keys(icons).map((name) => {
    // Convert PascalCase to kebab-case for display
    return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  });
}

// Get a subset of common/popular icons for quick selection
export const popularIcons = [
  'home',
  'user',
  'settings',
  'search',
  'star',
  'heart',
  'check',
  'x',
  'plus',
  'minus',
  'edit',
  'trash',
  'eye',
  'eye-off',
  'lock',
  'unlock',
  'mail',
  'phone',
  'map-pin',
  'calendar',
  'clock',
  'bell',
  'camera',
  'image',
  'file',
  'folder',
  'download',
  'upload',
  'share',
  'link',
  'external-link',
  'copy',
  'clipboard',
  'bookmark',
  'tag',
  'flag',
  'alert-circle',
  'info',
  'help-circle',
  'message-circle',
  'send',
  'inbox',
  'archive',
  'refresh-cw',
  'loader',
  'zap',
  'award',
  'gift',
  'shopping-cart',
  'credit-card',
  'dollar-sign',
  'percent',
  'bar-chart',
  'pie-chart',
  'trending-up',
  'trending-down',
  'activity',
  'wifi',
  'bluetooth',
  'battery',
  'sun',
  'moon',
  'cloud',
  'umbrella',
  'thermometer',
  'droplet',
  'wind',
  'compass',
  'navigation',
  'map',
  'globe',
  'building',
  'building-2',
  'home',
  'hotel',
  'warehouse',
  'store',
  'school',
  'hospital',
  'church',
  'landmark',
  'castle',
  'tent',
  'mountain',
  'tree',
  'flower',
  'leaf',
  'palm-tree',
  'car',
  'bus',
  'train',
  'plane',
  'ship',
  'bike',
  'truck',
  'parking',
  'fuel',
  'utensils',
  'coffee',
  'wine',
  'beer',
  'pizza',
  'cake',
  'cookie',
  'apple',
  'banana',
  'cherry',
  'carrot',
  'egg',
  'fish',
  'beef',
  'drumstick',
  'sandwich',
  'popcorn',
  'ice-cream',
  'candy',
  'dumbbell',
  'weight',
  'trophy',
  'medal',
  'target',
  'gamepad',
  'dice',
  'puzzle',
  'music',
  'headphones',
  'speaker',
  'mic',
  'video',
  'tv',
  'monitor',
  'smartphone',
  'tablet',
  'laptop',
  'printer',
  'keyboard',
  'mouse',
  'hard-drive',
  'cpu',
  'server',
  'database',
  'cloud-off',
  'shield',
  'key',
  'fingerprint',
  'scan',
  'qr-code',
  'barcode',
  'filter',
  'sort-asc',
  'sort-desc',
  'layers',
  'layout',
  'grid',
  'list',
  'columns',
  'rows',
  'table',
  'kanban',
  'gantt-chart',
  'network',
  'git-branch',
  'git-merge',
  'git-pull-request',
  'code',
  'terminal',
  'bug',
  'test-tube',
  'flask',
  'microscope',
  'atom',
  'dna',
  'pill',
  'syringe',
  'stethoscope',
  'heart-pulse',
  'brain',
  'hand',
  'thumbs-up',
  'thumbs-down',
  'hand-heart',
  'sparkles',
  'wand',
  'palette',
  'brush',
  'pen',
  'pencil',
  'ruler',
  'scissors',
  'eraser',
  'highlighter',
  'type',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'align-left',
  'align-center',
  'align-right',
  'align-justify',
  'indent',
  'outdent',
  'quote',
  'heading',
  'pilcrow',
  'list-ordered',
  'list-check',
  'chevron-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'arrow-up',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'move',
  'maximize',
  'minimize',
  'expand',
  'shrink',
  'rotate-cw',
  'rotate-ccw',
  'flip-horizontal',
  'flip-vertical',
  'zoom-in',
  'zoom-out',
  'scan-eye',
  'focus',
  'crop',
  'slice',
  'circle',
  'square',
  'triangle',
  'hexagon',
  'octagon',
  'pentagon',
  'diamond',
  'rectangle-horizontal',
  'rectangle-vertical',
  'box',
  'package',
  'archive-box',
  'briefcase',
  'suitcase',
  'backpack',
  'shopping-bag',
  'wallet',
  'receipt',
  'ticket',
  'badge',
  'id-card',
  'contact',
  'users',
  'user-plus',
  'user-minus',
  'user-check',
  'user-x',
  'users-round',
  'group',
  'crown',
  'gem',
  'diamond',
  'ring',
  'glasses',
  'sunglasses',
  'watch',
  'clock',
  'alarm-clock',
  'timer',
  'hourglass',
  'calendar-days',
  'calendar-check',
  'calendar-plus',
  'calendar-minus',
  'calendar-x',
  'calendar-clock',
  'calendar-heart',
  'party-popper',
  'confetti',
  'balloon',
  'fireworks',
  'sparkle',
  'stars',
  'sunrise',
  'sunset',
  'rainbow',
  'anchor',
  'sailboat',
  'waves',
  'pool',
  'bath',
  'shower',
  'toilet',
  'sink',
  'lamp',
  'lamp-desk',
  'lamp-floor',
  'lightbulb',
  'flashlight',
  'candle',
  'fire',
  'flame',
  'snowflake',
  'cloud-rain',
  'cloud-snow',
  'cloud-lightning',
  'tornado',
  'hurricane',
];
